### ISSUE TITLE
Access token missing from response

### ISSUE THREAD

**Issue by lstallocca** [Neuralab/WooCommerce-Salesforce-integration#1]
Hi, 
We implemented your plugin and was working verywell.
Buy mistake we delete it. and now that we reinstalled was unable to connect to Salesforce when we click on save changes of the key and the secret.
it give us this messsage "Access token missing from response, please try again!"

Any clue of what's going on?
Regards,

**Comment by matejbasic** [comment]
Hi,

We tried to recreate your bug but everything works fine. Could you please tell us what WP and WooCommerce versions are you using? 

Regards,
Matej, Neuralab Dev Team

**Comment by TomAlanko** [comment]
Hi,

Even if the callback URL on the integration tab displays the correct path, once hitting 'save changes' it loads URL without sub directory.  In my case 

redirect_uri=https%3A%2F%2Fwww.domain.org%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-settings%26tab%3Dintegration%26section%3Dnwsi

should be 

redirect_uri=https%3A%2F%2Fwww.domain.org%2Fwordpress%2Fwp-admin%2Fadmin.php%3Fpage%3Dwc-settings%26tab%3Dintegration%26section%3Dnwsi

Also, trying to connect to sandbox.  You should make it possible to change login URL from https://login.salesforce.com to another, for example https://cs43.salesforce.com/ while testing.

Even so, overcoming the both issues above, returns error message "Access token missing from response, please try again!".   Using latest versions of WP and Woo.

Where can I look to troubleshoot?

Thanks.

**Comment by danhowellnz** [comment]
Hello,

We have the same issue. I noticed that in Salesforce there are additional options to the youtube video. Under 'Selected OAuth Scopes' there is also:

Require Secret for Web Server Flow
Include ID Token
Enable Asset Tokens

Any ideas?

**Comment by Poertel** [comment]
I am having a similar issue connecting.  I am using Wordpress ver 4.7.3, and WooCommerce ver 2.6.14.  My Integration page looks different than the video.  Where do we get the tokens from?

![woocommerce integration](https://cloud.githubusercontent.com/assets/26284968/23719973/50bec97a-040b-11e7-960f-a60b7c5e4c9f.JPG)
Also, what should be the Callback URL we put in Salesforce Connected App settings?  Wordpress documentation says    https://yoursite.url/wc-api/CALLBACK/
![salesforce](https://cloud.githubusercontent.com/assets/26284968/23720303/573bfcae-040c-11e7-9c0a-8cdaf1d53540.JPG)

**Comment by TornMarketing** [comment]
Hey guys,

Has anyone found a solution for this as yet?
Also I don't have the WordPress page as above, got the one as per the video but hitting this error

Dwayne

**Comment by acs047** [comment]
Hey, 

I also have this problem, any solutions yet?

**Comment by acs047** [comment]
Hi guys, 

I found out that this problem occurs with sandbox, to resolve in the login url just  put: https://test.salesforce.com/

**Comment by mickael-clavier** [comment]
Same trouble for me. I tried to recreate many times but still the same message : Access token missing from response, please try again! So I'm unable to link Woocommerce and Salesforce :(

I have plugin 0.9 and WP 4.8.2 and WooCommerce 3.2.1

Have you an idea ?

**Comment by tannerm** [comment]
I also ran into this error when trying to connect to a sandbox account. Switching the login url to https://test.salesforce.com solved it for me too. Thanks @acs047!
