### ISSUE TITLE
No relationships or dropdown items

### ISSUE THREAD

**Issue by fitbodywrapadmin** [Neuralab/WooCommerce-Salesforce-integration#10]
Hello and good day, I came across this integration add-on for WordPress and this is EXACTLY what we have been searching, so I downloaded the zip file, I then uploaded it successfully to our WordPress site which is fully upto date as well as I manage and monitor all site and plugin updates. I then followed the instructions for setting up the new Connected App in Salesforce and waited 30 minutes just to be safe, I then put in the Key and Secret into the newly added integrations tab under WooCommerce settings. After clicking save, it appears to have been successful as it displays the floating message the the token was successful blah blah, however the default relationships do not populate and the relationships section shows blank, and when I try to create a new relationship the Salesforce dropdown also shows blank with nothing to be selected.

Can you please advise as soon as you can as I would like to get this operational quickly so our staff no longer have to manually add every online order into Salesforce?

Thanks in advance!

**Comment by brillantesmanuel** [comment]
any thoughts on this? need also help regarding this one.

**Comment by tannerm** [comment]
The problem has to do with the formatting of the json file. I just submitted a patch. If you replace the existing `default_relationships.json` with the one in the patch, the default relationships will show upon activation. 

WARNING! If you deactivate the plugin to re-activate it, any custom relationships that you've created will be deleted.

**Comment by matejbasic** [comment]
#7

**Comment by matejbasic** [comment]
Check the #7 issue
