### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ghost** [Neuralab/WooCommerce-Salesforce-integration#11]
Attempting to understand this link up, but just get lots of error messages...

Notice: Use of undefined constant NWSI_FOLDER_NAME - assumed 'NWSI_FOLDER_NAME' in /home/awwd/cvmdev.awwd.co.uk/wp-content/plugins/WooCommerce-Salesforce-integration-master/neuralab-woocommerce-salesforce-integration.php on line 56

**Comment by matejbasic** [comment]
Fixed. Check the #16 issue.
