### ISSUE TITLE
Error WoCommerce 

### ISSUE THREAD

**Issue by acs047** [Neuralab/WooCommerce-Salesforce-integration#12]
Hi, 

I'm getting this error when I click on save and  sync button. 

"Fatal error: Uncaught Error: Call to a member function read() on null in C:\xampp\htdocs\wp\wordpress\wp-content\plugins\woocommerce\includes\legacy\abstract-wc-legacy-order.php:628 Stack trace: #0 C:\xampp\htdocs\wp\wordpress\wp-content\plugins\WooCommerce-Salesforce-integration-master\includes\models\class-nwsi-order-model.php(23): WC_Abstract_Legacy_Order->init(18) #1 C:\xampp\htdocs\wp\wordpress\wp-content\plugins\WooCommerce-Salesforce-integration-master\includes\controllers\core\class-nwsi-salesforce-worker.php(80): NWSI_Order_Model->__construct(18) #2 C:\xampp\htdocs\wp\wordpress\wp-content\plugins\WooCommerce-Salesforce-integration-master\includes\views\class-nwsi-orders-view.php(45): NWSI_Salesforce_Worker->handle_order(18) #3 C:\xampp\htdocs\wp\wordpress\wp-includes\class-wp-hook.php(300): NWSI_Orders_View->process_order_sync_request(18) #4 C:\xampp\htdocs\wp\wordpress\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #5 C:\xampp\htdocs\wp\wordpress\wp-includes\plugin.php(453): WP_Hook->do_ in C:\xampp\htdocs\wp\wordpress\wp-content\plugins\woocommerce\includes\legacy\abstract-wc-legacy-order.php on line 628"

I can't figure out why, someone has any idea?

**Comment by acs047** [comment]
After some debuguing I figure out that the error comes from 
NWSI_Order_Model -> __Construct($order) -> parent::init($order)
int he parent class 
WC_Abstract_Legacy_Order -> init($order) 

$this->data_store->read($this); 

in this line of code, the object data_store it's empty and that's the error. 

Does anyone know how to fix this?

**Comment by dpinzon-paradiso** [comment]
Hello everyone, I have the same error, but it seems that it was implemented an a latest version of the plugin. i had anohter previous version, and there it works fine.

So, if you want considerate, could you use this previous until this current version be fixed.

**Comment by nacho-perez-crm** [comment]
Hi @dpinzon-paradiso, 
Could you specify wich version works?

**Comment by matejbasic** [comment]
@nPcBirchMaN this should be fixed with the https://github.com/Neuralab/WooCommerce-Salesforce-integration/commit/6d68c166ca073711da0627e19bc8dadad4226b38 commit.
Plugin is also updated to work wit the latest version of the Wordpress (4.9.7) platform and WooCommerce (3.4) plugin.
