### ISSUE TITLE
Relationship Section Missing

### ISSUE THREAD

**Issue by ltlmschrisss** [Neuralab/WooCommerce-Salesforce-integration#13]
Installed and connected successful but relationships section is still missing on the wp-admin/admin.php?page=wc-settings&tab=integration&section=nwsi page.

**Comment by matejbasic** [comment]
Solved with the https://github.com/Neuralab/WooCommerce-Salesforce-integration/commit/68cf4f9e9ef630e204227d79bbc5ea5922151f54 commit.
