### ISSUE TITLE
Can I use the plugin from localhost

### ISSUE THREAD

**Issue by sagarcosmos** [Neuralab/WooCommerce-Salesforce-integration#15]
I am trying to use the plugin from my localhost. At first it prompted to saleforce Allow access page. But not showing the page for further settings. 

It is showing the below error :- 

This site can’t be reached
localhost refused to connect.

**Comment by matejbasic** [comment]
@sagarpanwar0123 yes, but you should enable SSL. So for localhost you will need to create self-signed SSL certificate. Check this [article](https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-apache-in-ubuntu-16-04) for example.
