### ISSUE TITLE
Undefined constant - showing the error at line number 56

### ISSUE THREAD

**Issue by sagarcosmos** [Neuralab/WooCommerce-Salesforce-integration#16]
The below error is showing after installing the plugin. 
Undefined contant at line number 56 

I removed the line and working. Any suggestion. 
 
**if ( !defined( "NWSI_FOLDER_NAME" ) ) {
          define( NWSI_FOLDER_NAME, basename( __DIR__ ) );
        }**

**Comment by matejbasic** [comment]
Fixed!
Fyi, NWSI_FOLDER_NAME is now renamed to NWSI_DIR_NAME.
