### ISSUE TITLE
Fatal Error : Call to a member function read() , While sync 

### ISSUE THREAD

**Issue by sagarcosmos** [Neuralab/WooCommerce-Salesforce-integration#17]
Notice: WC_Order::init is deprecated since version 3.0! Use Logic moved to constructor instead. in ../labs/dev_wordpress/wp-includes/functions.php on line 3853

Fatal error: Call to a member function read() on null in ../labs/dev_wordpress/wp-content/plugins/woocommerce/includes/legacy/abstract-wc-legacy-order.php on line 628

Wordpress version : wordpress-4.9.7
woo commerce version: woocommerce.3.4.3

**Comment by matejbasic** [comment]
Same issue as #12
