### ISSUE TITLE
Not all woocommerce fields shown

### ISSUE THREAD

**Issue by Arnevv** [Neuralab/WooCommerce-Salesforce-integration#4]
Hi, 

I have installed your plugin and it is working to some extent. It seems like i'm missing some woocommerce fields in the mapping. I don't see for example the woocommerce field 'Billing Company'. 

I only see the following choices if i try to map the Account name for orders: 
- customer message
- order date
- modified date
- order type
'- custom value'

**Comment by getCascadia** [comment]
having the same issue here

**Comment by matejbasic** [comment]
Models are refactored in https://github.com/Neuralab/WooCommerce-Salesforce-integration/commit/2626d19fbe58905d354f27bdab73653e94a73c94 commit.
Now they are using data keys from from the extended WooCommerce classes such as WC_Order_Item, WC_Order and WC_Product.

If you still have a problem with missing fields, you can add them via filters:
"nwsi_order_item_property_keys"
"nwsi_order_property_keys"
"nwsi_product_property_keys"
for each type of the synced object.
Filter has one argument, $keys, which should be updated and returned.

Also, you have filters for each added filed:
"nwsi_get_order_item_property_key_{name_of_the_field}"
"nwsi_get_order_property_key_{name_of_the_field}"
"nwsi_get_product_property_key_{name_of_the_field}"
This filters should return a value for the field you added.
Check the mentioned commit for more details.

Matej
