### ISSUE TITLE
When trying to uninstall: "Deletion failed: Internal Server Error"

### ISSUE THREAD

**Issue by getCascadia** [Neuralab/WooCommerce-Salesforce-integration#5]
Was attempting to uninstall to reinstall. Believe you have an issue with removing related database entries during deactivation or deletion. 

I've uninstalled and reinstalled other plugins with no issue, and it is localized just to this one plugin.

We were able to remove the files via FTP, but upon reinstallation - all of the remaining database entries were still valid. 

Since we are unable to remove the related database entries we are unable to troubleshoot our other issue with the application #4.

**Comment by matejbasic** [comment]
@adamlouis365, unistallation procedure has been [fixed](https://github.com/Neuralab/WooCommerce-Salesforce-integration/commit/eeee0da1f41525588e6aabe18bb5bc45f5866b21).
Problem was in the wrong path to a DB class. 

Kind regards,
Matej, Neuralab
