### ISSUE TITLE
Error when trying to sync order

### ISSUE THREAD

**Issue by lmartins** [Neuralab/WooCommerce-Salesforce-integration#6]
Hi,

I've gone through the configuration steps, enabled automatic order sync and all relationships as shown here: 
![screen shot 2017-01-26 at 09 54 32](https://cloud.githubusercontent.com/assets/151981/22327116/76b5b96e-e3ad-11e6-8452-612e0d8e1e0f.png)

When I first tried to manually an existing order, it said something about a unknown account. After that, of later attempts it know says:
```
1. REQUIRED_FIELD_MISSING (Account): Required fields are missing: [Name]
```

When attempting to sync other orders, it still throws the same error:
![screen shot 2017-01-26 at 09 53 41](https://cloud.githubusercontent.com/assets/151981/22327094/595673f4-e3ad-11e6-8738-c0d4486aa2dc.png)

Any idea of what might be going wrong?

**Comment by matejbasic** [comment]
Hi,

I would say that there's no value in the order's field related to Account Name which is required in Salesforce. By default that's Billing Company.
![image](https://cloud.githubusercontent.com/assets/4060253/22433976/98fc436a-e71a-11e6-8781-4c094708139a.png)

You can always change field related to Account Name or set Billing Company to be required at the checkout. Let us know if this solved your problem!

Kind regards,
Matej, Neuralab
