### ISSUE TITLE
No default relationships

### ISSUE THREAD

**Issue by shayatik** [Neuralab/WooCommerce-Salesforce-integration#7]
Hey @matejbasic .

I Installed the plugin, added consumer key and secret, connection was successful but there are no default relationships. How can I install the default relationships?

**Comment by matejbasic** [comment]
Hi @shayatik,

did you got any error messages during the installation?

Kind regards,
Matej, Neuralab

**Comment by shayatik** [comment]
Nope, nothing. Anyway I copied all the default relationships manually from default_relationships.json

**Comment by matejbasic** [comment]
That's strange. We'll leave this ticket open for a while and try to recreate a bug. Maybe there was something wrong with the reading permissions of the default_relationships.json.

**Comment by BPMUK** [comment]
I am also having this problem - any ideas?

**Comment by tannerm** [comment]
The problem has to do with the formatting of the json file. I just submitted a patch. If you replace the existing `default_relationships.json` with the one in the patch, the default relationships will show upon activation. 

WARNING! If you deactivate the plugin to re-activate it, any custom relationships that you've created will be deleted.

**Comment by Kulvinderjatt** [comment]
Hi, 

I am having the same issue. Replaced the mentioned default_relationships.json file at my integration, but still not showing any default relationships. Help me fixing this please.

Thanks,
Kulvinder

**Comment by Kulvinderjatt** [comment]
I deactivated and reactivated the plugin after replacing the above-mentioned file, It picked the default relations ships but have these errors: 

In order, I can see this error:
1. NWSI: No defined relationships.

Here are some screenshots

[Edit_order_‹_Managed_Security_Services_Provider___IT_Security___PCI_Compliance_—_WordPress.pdf](https://github.com/Neuralab/WooCommerce-Salesforce-integration/files/2150277/Edit_order_._Managed_Security_Services_Provider___IT_Security___PCI_Compliance_._WordPress.pdf)
[WooCommerce_settings_‹_Managed_Security_Services_Provider___IT_Security___PCI_Compliance_—_WordPress.pdf](https://github.com/Neuralab/WooCommerce-Salesforce-integration/files/2150278/WooCommerce_settings_._Managed_Security_Services_Provider___IT_Security___PCI_Compliance_._WordPress.pdf)

**Comment by Kulvinderjatt** [comment]
I placed another order, Now i am unable to save and sync the order.

**Comment by Kulvinderjatt** [comment]
Hey guys- and is there any update on this?

**Comment by matejbasic** [comment]
This should be fixed with the https://github.com/Neuralab/WooCommerce-Salesforce-integration/commit/68cf4f9e9ef630e204227d79bbc5ea5922151f54 commit. 

@Kulvinderjatt if you have any other problem, please open a new issue.

**Comment by Kulvinderjatt** [comment]
Thanks for responding, I will go through the above commit.

**Comment by kmiths19** [comment]
I am facing this same issue now. Can you please let me know how can I fix this?
