### ISSUE TITLE
Nothing showing in dropdown box for Salesforce

### ISSUE THREAD

**Issue by dburton77** [Neuralab/WooCommerce-Salesforce-integration#8]
Hi,

First of all, thank you for developing this plugin. I think it going to work great for us. However, once we added the Callback URL to the Salesforce Connected App and add the Consumer Key and Consumer Secret in the fields on the Integration tab, and saved, the Salesforce dropbox is empty. Alas, orders are not synching. Any ideas? 

Also, I noticed there's an extra field that was not in the demo video. It's for Login URL and it autpopulates with https://login.salesforce.com

Is this correct?

Doug

**Comment by aureliendebord** [comment]
Hello,
Same problem for me.

Aurélien

**Comment by cwhittl** [comment]
In class-nswi-salesforce.php change your timeout on line 28 to 20 (or more)

It's timing out.

**Comment by matejbasic** [comment]
@cwhittl that's right, thank you! With the updated version of the plugin, 1.0, we'll also add these kind of settings so you won't need to go through the code.
